[project]
name = "fastapi-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "syedtanzeelshaz", email = "syedtanzeelshaz@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
fastapi-proj = "fastapi_proj:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
